### PR TITLE
Some improvements to the fake table navigation

### PR DESCRIPTION
**Pull request by javidominguez**

### CODE REVIEW

**Comment by nvdaes** [comment]
Sorry so much, just seeing this now! I'll change notifications to receive emails when someone creates a pull request. I'll review it and merge @javidominguez

**Review by nvdaes — APPROVED** [review]

**Comment by nvdaes** [comment]
Sorry @javidominguez . I've tested this and it doesn't work as expected.

- In list of servers, pressing control+NVDA+0, the server name is not read, and seems that this column cannot be disabled
- - Trying to read column 11 or others, even when they are enabled, these columns cannot be read
I liked the code and the idea, but for now these are my results, so I'll revert this change. Please feel free to reopen this PR or create a new one if you know how this can be improved.

Thanks

**Comment by javidominguez** [comment]
Long time ago and I don't remember it well but I do not know what is the problem.

control+NVDA+number reads columns 1 to 10 (0 is column 10); shift+NVDA+number reads column 11 to 20 (1=11, 2=12, 3=13, until 0=20). This is not mine, it worked exactly the same before my modification.

With my modification, ignoring hidden columns, in the list of servers instead of 16 there are 13 columns. If with shift + NVDA + 0 you try to read column 20 that does not exist, the normal thing is that it does not read it. If you want to read the name of the server press control + NVDA + 1.

Also, my function only skips the columns that NVDA can reach with the object navigator but are not actually drawn on the screen. They are in the object tree but have the state STATE_INVISIBLE.

**Comment by javidominguez** [comment]
Sorry, I was wrong. You said "control" and I understood "shift".
  
  control + NVDA + 0 corresponds to column 10. When hiding columns it remains in position 8. In my case it reads "preference: normal".

**Comment by nvdaes** [comment]
OK. If you feel this can be improved, you mey create a new PR if you want to fill in the template set for all my add-ons, or reopen this one, since your purpose can be understood well.
If you create anew one using GitHub CLI, you may commit changes in a local branch as usually, and then type: gh pr create -w
I use this command a lot to create a PR and open the web browser to provide info.

**Pull request merged**
